Repository kyma-project/kyma-metrics-collector, pull requests merged in 2024-09, with the labels that each got.

#78 docs: add mandatory sections to readme
  README.md
Labels: cla: yes, lgtm, size/S

#79 chore: add missing parts for reuse compliance
  .reuse/dep5
  README.md
Labels: cla: yes, lgtm, size/S

#83 chore: added missing licenses folder
  .gitignore
  LICENSES/Apache-2.0.txt
Labels: size/M, cla: yes, lgtm

#91 chore: add github checks
  .github/workflows/pr-github-checks.yml
Labels: size/M, cla: yes, lgtm, kind/chore

#92 chore: Remove duplicate title check
  .github/workflows/lint-conventional-prs.yml
Labels: size/M, cla: yes, lgtm, kind/chore

#95 chore: Add docs and chore to enhancements
  .github/release.yml
Labels: cla: yes, lgtm, size/XS, area/release, kind/chore

#86 chore: Migrate workflow from Prow to GitHub Actions
  .github/workflows/build-image.yml
Labels: size/M, cla: yes, lgtm, area/ci, kind/chore
