Repository kyma-project/kyma-metrics-collector, pull requests merged in 2024-11, with the labels that each got.

#110 chore: Switch release to build-image
  .github/workflows/build-image.yml
  .github/workflows/create-release.yml
  hack/scripts/await_image.sh
  hack/scripts/create_sec_scanner_bump_pr.sh
  hack/scripts/releaselabelvalidator/release_label_validator.py
  sec-scanners-config.yaml
Labels: cla: yes, area/ci, kind/chore, lgtm, size/M

#112 chore: Use build image directly
  .github/workflows/create-release.yml
  .github/workflows/pr-all-checks-passed.yml
  sec-scanners-config.yaml
Labels: cla: yes, area/release, kind/chore, size/M

#114 chore: Fix typo in gha definition
  .github/workflows/create-release.yml
  sec-scanners-config.yaml
Labels: cla: yes, area/release, kind/chore, lgtm, size/XS

#116 feat: New metrics for internal queues
  Makefile
  cmd/main.go
  docs/contributor/metrics.md
  hack/metrics.md.tpl
  internal/tools/go.mod
  internal/tools/tools.go
  options/options.go
  pkg/cache/kubeconfig.go
  pkg/cache/metrics.go
  pkg/edp/client.go
  pkg/edp/client_test.go
  pkg/keb/client.go
  pkg/keb/client_test.go
  pkg/logger/logger.go
  pkg/process/event_stream.go
  pkg/process/event_stream_test.go
  pkg/process/keb_processing.go
  pkg/process/metrics.go
  pkg/process/process.go
  pkg/process/process_test.go
  pkg/process/public_cloud_info.go
  pkg/process/public_cloud_info_test.go
  pkg/process/queue_processing.go
  pkg/queue/metrics.go
  pkg/queue/queue.go
  pkg/service/server.go
  pkg/skr/commons/helpers.go
  pkg/skr/commons/metrics.go
  pkg/skr/node/client.go
  pkg/skr/node/client_test.go
  pkg/skr/node/fake.go
  pkg/skr/pvc/client.go
  pkg/skr/pvc/client_test.go
  pkg/skr/pvc/fake.go
  pkg/skr/svc/client.go
  pkg/skr/svc/client_test.go
  pkg/skr/svc/fake.go
  pkg/testing/helpers.go
Labels: cla: yes, kind/feature, lgtm, size/XXL, area/monitoring

#118 feat: Add support for Redis
  cmd/main.go
  env/config.go
  go.mod
  go.sum
  pkg/process/event_stream.go
  pkg/process/event_stream_test.go
  pkg/process/process.go
  pkg/process/process_test.go
  pkg/process/public_cloud_info.go
  pkg/process/public_cloud_specs.go
  pkg/process/public_cloud_specs_test.go
  pkg/process/queue_processing.go
  pkg/skr/commons/helpers.go
  pkg/skr/commons/metrics.go
  pkg/skr/redis/client.go
  pkg/skr/redis/client_test.go
  pkg/skr/redis/config.go
  pkg/skr/redis/fake.go
  pkg/testing/fixtures/public_cloud_specs.json
  pkg/testing/fixtures/public_cloud_specs_no_aws.json
  pkg/testing/fixtures/public_cloud_specs_no_azure.json
  pkg/testing/fixtures/public_cloud_specs_no_ccee.json
  pkg/testing/fixtures/public_cloud_specs_no_gcp.json
  pkg/testing/fixtures/public_cloud_specs_no_redis.json
  pkg/testing/fixtures/static_providers.json
  pkg/testing/helpers.go
Labels: cla: yes, kind/feature, size/XXL, area/monitoring

#123 feat: Add interfaces for new scanner implementation
  .golangci.yaml
  Makefile
  docs/contributor/arch/01-collector-structure.md
  go.mod
  go.sum
  pkg/collector/edp/collector.go
  pkg/collector/edp/record.go
  pkg/collector/interface.go
  pkg/collector/unifiedmetering/collector.go
  pkg/collector/unifiedmetering/record.go
  pkg/resource/interface.go
  pkg/resource/redis/scan.go
  pkg/resource/redis/scanner.go
  pkg/resource/structures.go
Labels: cla: yes, kind/feature, size/L, lgtm, area/codequality

#129 docs: Fix link to architecture diagram
  docs/contributor/README.md
Labels: cla: yes, area/documentation, kind/docs, lgtm, size/XS
