Repository kyma-project/kyma-metrics-collector, pull requests merged in 2024-12, with the labels that each got.

#128 chore: Add resource scanners
  cmd/main.go
  go.mod
  go.sum
  pkg/collector/edp/collector.go
  pkg/collector/interface.go
  pkg/collector/unifiedmetering/collector.go
  pkg/config/public_cloud_specs.go
  pkg/config/public_cloud_specs_test.go
  pkg/otel/otel.go
  pkg/process/event_stream.go
  pkg/process/event_stream_test.go
  pkg/process/process.go
  pkg/process/process_test.go
  pkg/process/queue_processing.go
  pkg/resource/interface.go
  pkg/resource/node/scan.go
  pkg/resource/node/scan_test.go
  pkg/resource/node/scanner.go
  pkg/resource/node/scanner_test.go
  pkg/resource/pvc/scan.go
  pkg/resource/pvc/scan_test.go
  pkg/resource/pvc/scanner.go
  pkg/resource/pvc/scanner_test.go
  pkg/resource/redis/scan.go
  pkg/resource/redis/scan_test.go
  pkg/resource/redis/scanner.go
  pkg/resource/redis/scanner_test.go
  pkg/resource/structures.go
  pkg/runtime/runtime.go
  pkg/testing/helpers.go
Labels: cla: yes, kind/chore, lgtm, size/XXL, area/codequality

#131 docs: Update edp schema to latest production version
  docs/contributor/README.md
  docs/contributor/assets/edp.json
Labels: cla: yes, area/documentation, kind/docs, size/L, lgtm

#139 chore: Exclude checks during merge_group
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
Labels: cla: yes, area/ci, kind/chore, lgtm, size/XS

#140 chore: Group otel dependencies
  .github/dependabot.yml
Labels: cla: yes, area/ci, kind/chore, lgtm, size/XS

#135 chore: Implement collector interface for EDP
  .golangci.yaml
  cmd/main.go
  pkg/cache/record.go
  pkg/collector/edp/client.go
  pkg/collector/edp/client_test.go
  pkg/collector/edp/collector.go
  pkg/collector/edp/collector_test.go
  pkg/collector/edp/config.go
  pkg/collector/edp/metrics.go
  pkg/collector/edp/payload.go
  pkg/collector/edp/record.go
  pkg/collector/edp/stubs/scan.go
  pkg/collector/edp/stubs/scanner.go
  pkg/collector/metrics.go
  pkg/edp/consumption_metrics.go
  pkg/logger/logger.go
  pkg/otel/span_attributes.go
  pkg/process/event_stream.go
  pkg/process/event_stream_test.go
  pkg/process/keb_processing.go
  pkg/process/metrics.go
  pkg/process/process.go
  pkg/process/process_test.go
  pkg/process/queue_processing.go
  pkg/process/stubs/collector.go
  pkg/process/stubs/scan.go
  pkg/resource/node/scanner.go
  pkg/resource/node/scanner_test.go
  pkg/resource/pvc/scanner.go
  pkg/resource/redis/scanner.go
  pkg/resource/vsc/scanner.go
  pkg/runtime/runtime.go
  pkg/skr/commons/helpers.go
  pkg/skr/commons/metrics.go
  pkg/skr/node/client.go
  pkg/skr/node/client_test.go
  pkg/skr/node/config.go
  pkg/skr/node/fake.go
  pkg/skr/pvc/client.go
  pkg/skr/pvc/client_test.go
  pkg/skr/pvc/config.go
  pkg/skr/pvc/fake.go
  pkg/skr/redis/client.go
  pkg/skr/redis/client_test.go
  pkg/skr/redis/config.go
  pkg/skr/redis/fake.go
  pkg/skr/svc/client.go
  pkg/skr/svc/client_test.go
  pkg/skr/svc/config.go
  pkg/skr/svc/fake.go
Labels: cla: yes, kind/chore, lgtm, size/XXL, area/codequality
