Repository kyma-project/kyma-metrics-collector, pull requests merged in 2024-03, with the labels that each got.

#6 chore: updated codeowners and gitignore
  .gitignore
  CODEOWNERS
Labels: size/M, cla: yes, lgtm

#7 fix: fix go module path and update makefile
  Dockerfile
  Makefile
  cmd/main.go
  dev/deployment.yaml
  go.mod
  pkg/cache/record.go
  pkg/edp/client.go
  pkg/edp/client_test.go
  pkg/edp/metrics.go
  pkg/keb/client.go
  pkg/keb/client_test.go
  pkg/keb/metrics.go
  pkg/process/event_stream.go
  pkg/process/event_stream_test.go
  pkg/process/metrics.go
  pkg/process/process.go
  pkg/process/process_test.go
  pkg/process/public_cloud_info.go
  pkg/process/public_cloud_info_test.go
  pkg/service/server.go
  pkg/skr/commons/metrics.go
  pkg/skr/node/client.go
  pkg/skr/node/client_test.go
  pkg/skr/node/config.go
  pkg/skr/node/fake.go
  pkg/skr/pvc/client.go
  pkg/skr/pvc/client_test.go
  pkg/skr/pvc/config.go
  pkg/skr/pvc/fake.go
  pkg/skr/svc/client.go
  pkg/skr/svc/client_test.go
  pkg/skr/svc/config.go
  pkg/skr/svc/fake.go
Labels: cla: yes, lgtm, size/L

#8 chore: added unit tests github action
  .github/workflows/test.yml
Labels: cla: yes, lgtm, size/S

#9 chore: added sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: cla: yes, lgtm, size/XS

#10 chore: added PR title lint job
  .github/workflows/lint-conventional-prs.yml
Labels: size/M, cla: yes, lgtm

#11 chore: updated documentation
  Makefile
  README.md
  metrics.md
  pkg/process/metrics.go
Labels: size/M, cla: yes, lgtm

#14 chore: enable-dependabot
  .github/dependabot.yml
Labels: size/M, cla: yes, lgtm

#16 chore: implement automated release workflow - part 1
  .github/release.yml
  .github/workflows/create-release.yml
  .gitignore
  hack/scripts/await_pr_merge.sh
  hack/scripts/check_artifacts_existence.sh
  hack/scripts/create_scan_config.sh
  hack/scripts/create_sec_scanner_bump_pr.sh
  hack/scripts/releaselabelvalidator/release_label_validator.py
  hack/scripts/releaselabelvalidator/requirements.txt
Labels: cla: yes, lgtm, size/L

#23 fix: fixed commit ref for release pipeline
  .github/workflows/create-release.yml
  hack/scripts/check_artifacts_existence.sh
Labels: cla: yes, lgtm, size/XS

#27 refactor: removed helm chart from upstream
  .github/workflows/create-release.yml
  hack/scripts/bump_kmc_chart.sh
  hack/scripts/check_publish_release_prerequisites.sh
  hack/scripts/create_bump_kmc_chart_pr.sh
  hack/scripts/upload_assets.sh
  resources/kyma-metrics-collector/.helmignore
  resources/kyma-metrics-collector/Chart.yaml
  resources/kyma-metrics-collector/templates/_helpers.tpl
  resources/kyma-metrics-collector/templates/deployment.yaml
  resources/kyma-metrics-collector/templates/policy.yaml
  resources/kyma-metrics-collector/templates/prometheusrule.yaml
  resources/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
  resources/kyma-metrics-collector/templates/role.yaml
  resources/kyma-metrics-collector/templates/rolebinding.yaml
  resources/kyma-metrics-collector/templates/secrets.yaml
  resources/kyma-metrics-collector/templates/service-account.yaml
  resources/kyma-metrics-collector/templates/service-monitor.yaml
  resources/kyma-metrics-collector/templates/service.yaml
  resources/kyma-metrics-collector/templates/vm-service-scrape.yaml
  resources/kyma-metrics-collector/values.yaml
Labels: cla: yes, lgtm, size/XXL

#29 fixed: fixed needs for publish-release step in create release workflow
  .github/workflows/create-release.yml
Labels: cla: yes, lgtm, size/XS

#31 fixed: fixed needs for publish-release step in create release workflow
  .github/workflows/create-release.yml
Labels: cla: yes, lgtm, size/XS

#32 chore: enabled validate labels step in create release workflow
  .github/workflows/create-release.yml
Labels: size/M, cla: yes, lgtm
