Repository kyma-project/kyma-metrics-collector, pull requests merged in 2024-10, with the labels that each got.

#99 chore: Update lint config
  .gitignore
  .golangci.yaml
  Makefile
  internal/tools/go.mod
  internal/tools/go.sum
  internal/tools/tools.go
  pkg/process/event_stream_test.go
  pkg/process/process_test.go
  pkg/process/public_cloud_info_test.go
Labels: cla: yes, area/ci, kind/chore, lgtm, size/XXL

#100 chore: Update dependant config and makefile for tools package
  .github/dependabot.yml
  .github/template/setup-golang/action.yaml
  .github/workflows/build-image.yml
  .github/workflows/lint-go.yml
  .github/workflows/pr-all-checks-passed.yml
  .github/workflows/pr-code-checks.yml
  .github/workflows/pr-docu-checks.yml
  .github/workflows/pr-github-checks.yml
Labels: cla: yes, area/ci, kind/chore, lgtm, size/M

#88 feat: Introduce internal docu
  README.md
  docs/README.md
  docs/contributor/README.md
  docs/contributor/assets/arch.drawio.svg
  docs/contributor/assets/edp.json
  docs/contributor/metrics.md
  docs/contributor/releasing.md
  docs/user/README.md
  docs/user/_sidebar.md
Labels: cla: yes, kind/feature, area/documentation, lgtm, size/XXL
