Repository kyma-project/kyma-metrics-collector, pull requests merged in 2025-02, with the labels that each got.

#169 chore: Rename fields in security config
  sec-scanners-config.yaml
Labels: cla: yes, area/release, kind/chore, lgtm, size/XS

#167 fix: Memleak in client-go transport
  cmd/main.go
  pkg/collector/edp/collector.go
  pkg/collector/edp/collector_test.go
  pkg/collector/edp/stubs/scanner.go
  pkg/collector/interface.go
  pkg/collector/unifiedmetering/collector.go
  pkg/metrics/metrics.go
  pkg/process/keb_processing.go
  pkg/process/metrics.go
  pkg/process/process.go
  pkg/process/process_test.go
  pkg/process/queue_processing.go
  pkg/process/stubs/collector.go
  pkg/resource/interface.go
  pkg/resource/node/scanner.go
  pkg/resource/node/scanner_test.go
  pkg/resource/pvc/scanner.go
  pkg/resource/pvc/scanner_test.go
  pkg/resource/redis/scanner.go
  pkg/resource/redis/scanner_test.go
  pkg/resource/vsc/scanner.go
  pkg/resource/vsc/scanner_test.go
  pkg/runtime/clients.go
  pkg/runtime/interfaces.go
  pkg/runtime/kubeconfigprovider/kubeconfig.go
  pkg/runtime/kubeconfigprovider/kubeconfig_test.go
  pkg/runtime/kubeconfigprovider/metrics.go
  pkg/runtime/kubeconfigprovider/record.go
  pkg/runtime/runtime.go
  pkg/runtime/stubs/clients.go
Labels: kind/bug, cla: yes, lgtm, size/XL, area/ResourceScanning

#171 chore: Remove dead config code
  pkg/config/public_cloud_specs.go
  pkg/config/public_cloud_specs_test.go
  pkg/testing/fixtures/public_cloud_specs.json
  pkg/testing/fixtures/public_cloud_specs_no_aws.json
  pkg/testing/fixtures/public_cloud_specs_no_azure.json
  pkg/testing/fixtures/public_cloud_specs_no_ccee.json
  pkg/testing/fixtures/public_cloud_specs_no_gcp.json
  pkg/testing/fixtures/public_cloud_specs_no_redis.json
Labels: cla: yes, kind/chore, size/L, lgtm, area/codequality

#168 chore: Update to golang 1.23.6
  .github/dependabot.yml
  Dockerfile
  go.mod
  go.sum
  internal/tools/go.mod
Labels: cla: yes, area/dependency, kind/chore, lgtm, size/S

#179 chore: Change title validation to lower case
  .github/workflows/pr-github-checks.yml
Labels: cla: yes, area/ci, kind/chore, lgtm, size/XS

#187 chore: (pvc, nfs) use nfs capacity label as primary source of truth
  pkg/resource/pvc/scan.go
  pkg/resource/pvc/scan_test.go
Labels: cla: yes, kind/chore, lgtm, size/M, area/UsageReporting

#188 chore: enable label and milestone automation
  .github/workflows/pr-github-checks.yml
  .github/workflows/titleprefix_to_label.json
  renovate.json
Labels: cla: yes, area/ci, kind/chore, size/L, lgtm

#189 chore: update golang builder to official 1.24.0
  Dockerfile
Labels: cla: yes, area/ci, kind/chore, lgtm, size/XS

#194 chore: enable gha update, disable dependabot
  renovate.json
Labels: cla: yes, area/ci, kind/chore, lgtm, size/XS

#200 fix: missing clientfactory crashes kmc on startup
  cmd/main.go
  pkg/process/process.go
  pkg/runtime/clients.go
Labels: kind/bug, cla: yes, area/tests, lgtm, size/M

#201 feat: filter suspended runtimes
  docs/contributor/README.md
  pkg/process/cluster_tracking.go
  pkg/process/cluster_tracking_test.go
  pkg/process/keb_processing.go
  pkg/process/process_test.go
  pkg/testing/helpers.go
Labels: cla: yes, kind/feature, lgtm, size/XL, area/ResourceScanning

#204 chore: disable dependabot
  .github/dependabot.yml
Labels: cla: yes, area/ci, kind/chore, lgtm, size/M

#208 chore: Bump x/oauth2 dependency
  go.mod
  go.sum
Labels: cla: yes, area/dependency, kind/chore, lgtm, size/XS
