Repository kyma-project/kyma-metrics-collector, pull requests merged in 2025-01, with the labels that each got.

#151 fix: Check if status is set in vsc handling
  pkg/collector/edp/collector.go
  pkg/resource/vsc/scan.go
  pkg/resource/vsc/scan_test.go
Labels: kind/bug, cla: yes, area/tests, lgtm, size/M

#153 chore: Update retry-go k8s.io/utils and x/net libraries
  go.mod
  go.sum
  internal/tools/go.mod
Labels: cla: yes, area/ci, kind/chore, lgtm, size/M

#155 chore: Remove bumping of sec-scanner-config during release
  .github/workflows/create-release.yml
  hack/scripts/await_pr_merge.sh
  hack/scripts/create_scan_config.sh
  hack/scripts/create_sec_scanner_bump_pr.sh
  sec-scanners-config.yaml
Labels: cla: yes, area/ci, kind/chore, size/L, lgtm

#156 fix: Fix Release
  hack/scripts/check_publish_release_prerequisites.sh
Labels: kind/bug, cla: yes, area/ci, lgtm, size/XS

#157 chore: Fix publish release step
  .github/workflows/create-release.yml
Labels: cla: yes, area/ci, kind/chore, lgtm, size/XS

#158 chore: Dont cache Kubeconfigs twice
  cmd/main.go
  options/options.go
  pkg/cache/kubeconfig.go
  pkg/collector/edp/collector.go
  pkg/keb/client.go
  pkg/kubeconfigprovider/kubeconfig.go
  pkg/kubeconfigprovider/kubeconfig_test.go
  pkg/kubeconfigprovider/metrics.go
  pkg/kubeconfigprovider/record.go
  pkg/process/keb_processing.go
  pkg/process/metrics.go
  pkg/process/process.go
  pkg/process/process_test.go
  pkg/process/queue_processing.go
Labels: cla: yes, kind/chore, lgtm, size/XL, area/codequality

#163 chore: Update to golang 1.23.5
  Dockerfile
  go.mod
  internal/tools/go.mod
Labels: cla: yes, area/dependency, kind/chore, lgtm, size/XS

#164 chore: Migrate to checkmarx
  sec-scanners-config.yaml
Labels: cla: yes, area/ci, kind/chore, lgtm, size/XS

#166 chore: Fix checkmarx config
  sec-scanners-config.yaml
Labels: area/ci, kind/chore, lgtm, size/XS
