Repository kyma-project/kyma-metrics-collector, pull requests merged in 2025-04, with the labels that each got.

#231 chore: update gh action to proper release versions
  .github/workflows/build-image.yml
  .github/workflows/pr-all-checks-passed.yml
  .github/workflows/pr-github-checks.yml
  renovate.json
Labels: area/dependency, kind/chore

#234 chore: update x-net dependency
  go.mod
  go.sum
  internal/tools/go.mod
  internal/tools/go.sum
Labels: area/dependency, kind/chore

#236 chore: update x/net lib
  go.mod
  go.sum
  internal/tools/go.mod
  internal/tools/go.sum
Labels: area/dependency, kind/chore

#229 feat: add filtering of the clusters
  cmd/main.go
  options/options.go
  pkg/process/filter_clusters.go
  pkg/process/filter_clusters_test.go
  pkg/process/keb_processing.go
  pkg/process/process.go
  pkg/process/process_test.go
Labels: kind/feature, area/UsageReporting

#243 chore: add missing privileges
  .github/workflows/create-release.yml
Labels: area/release, kind/chore
